on:
  push:
    branches:
      - master
  schedule:
    - cron: 5 16 * * *

jobs:
  Bilibili-Manga:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Main
        uses: ./
        env:
          account: ${{ secrets.ACCOUNT }}
          password: ${{ secrets.PASSWORD }}
          push_key: ${{ secrets.PUSH_KEY }}
